#!/bin/bash
set -e

echo "📦 Syncing database schema via db push..."
npx prisma db push

TIMESTAMP=$(date +%Y%m%d%H%M%S)

# Clean old migrations to avoid conflicts
rm -rf prisma/migrations

mkdir -p "prisma/migrations/${TIMESTAMP}_init"

# Create migration_lock.toml
cat > "prisma/migrations/migration_lock.toml" <<- 'EOF'
# Please do not edit this file manually
# It should be added in your version-control system (i.e. Git)
provider = "postgresql"
EOF

# Extract DATABASE_URL from .env
DB_URL=$(grep -oP '^DATABASE_URL=\K.*' .env)

echo "📝 Creating migration SQL..."
npx prisma migrate diff \
  --from-empty \
  --to-url "$DB_URL" \
  --script \
  > "prisma/migrations/${TIMESTAMP}_init/migration.sql"

echo "📌 Marking migration ${TIMESTAMP}_init as applied..."
CHECKSUM=$(sha256sum "prisma/migrations/${TIMESTAMP}_init/migration.sql" | cut -d' ' -f1)
UUID=$(python3 -c "import uuid; print(uuid.uuid4())" 2>/dev/null)

# Parse credentials from DATABASE_URL
DB_USER=$(echo "$DB_URL" | sed -n 's|.*://\([^:]*\):.*|\1|p')
DB_PASS=$(echo "$DB_URL" | sed -n 's|.*://[^:]*:\([^@]*\)@.*|\1|p')
DB_HOST=$(echo "$DB_URL" | sed -n 's|.*@\([^:]*\):.*|\1|p')
DB_PORT=$(echo "$DB_URL" | sed -n 's|.*:\([0-9]*\)/.*|\1|p')
DB_NAME=$(echo "$DB_URL" | sed -n 's|.*/\([^?]*\).*|\1|p')

PGPASSWORD="$DB_PASS" psql -U "$DB_USER" -h "$DB_HOST" -p "$DB_PORT" -d "$DB_NAME" -c "
DELETE FROM _prisma_migrations WHERE migration_name = '${TIMESTAMP}_init';
INSERT INTO _prisma_migrations (id, checksum, finished_at, migration_name, started_at, applied_steps_count)
VALUES ('$UUID', '$CHECKSUM', NOW(), '${TIMESTAMP}_init', NOW(), 1);
" 2>&1 | grep -v "^DELETE\|^INSERT"

echo "🔄 Regenerating Prisma client..."
npx prisma generate

echo "✅ Database is up to date!"
echo "   Migration: ${TIMESTAMP}_init"
